export const meta = {
  id: "python-basics",
  title: "Python Basics",
  description: "Built-ins, slicing, strings, dicts, comprehensions",
  topics: ["Built-ins", "Slicing", "Strings", "Dicts", "Comprehensions"],
};

export const questions = [
  // --- MULTIPLE CHOICE ---
  {
    id: "mc1",
    type: "mc",
    topic: "Built-ins",
    question: "What does sum([1, 2, 3], 10) return?",
    options: ["6", "16", "10", "Error"],
    answer: "16",
    explanation: "sum() accepts an optional start value as the second argument. 1+2+3+10 = 16.",
    link: "https://docs.python.org/3/library/functions.html#sum",
  },
  {
    id: "mc2",
    type: "mc",
    topic: "Slicing",
    question: "What is the output of [0, 1, 2, 3, 4][1:4]?",
    options: ["[0, 1, 2, 3]", "[1, 2, 3, 4]", "[1, 2, 3]", "[2, 3, 4]"],
    answer: "[1, 2, 3]",
    explanation: "Slicing is start-inclusive, end-exclusive. Indices 1, 2, 3 → [1, 2, 3].",
    link: "https://docs.python.org/3/library/stdtypes.html#common-sequence-operations",
  },
  {
    id: "mc3",
    type: "mc",
    topic: "Slicing",
    question: "What does my_list[::-1] do?",
    options: [
      "Returns the last element",
      "Reverses the list",
      "Returns every other element",
      "Removes the last element",
    ],
    answer: "Reverses the list",
    explanation: "Step of -1 walks the list backwards from end to start — a classic reversal trick.",
    link: "https://docs.python.org/3/library/stdtypes.html#common-sequence-operations",
  },
  {
    id: "mc4",
    type: "mc",
    topic: "Slicing",
    question: "Given lst = [10, 20, 30, 40, 50], what is lst[::2]?",
    options: ["[10, 30, 50]", "[20, 40]", "[10, 20]", "[50, 30, 10]"],
    answer: "[10, 30, 50]",
    explanation: "Step of 2 picks every other element starting from index 0: 10, 30, 50.",
    link: "https://docs.python.org/3/library/stdtypes.html#common-sequence-operations",
  },
  {
    id: "mc5",
    type: "mc",
    topic: "Built-ins",
    question: "Which call returns the index of the maximum value in a list?",
    options: [
      "max(lst)",
      "lst.index(max(lst))",
      "lst.max_index()",
      "argmax(lst)",
    ],
    answer: "lst.index(max(lst))",
    explanation: "Python has no built-in argmax. Combine max() to get the value, then .index() to find its position.",
    link: "https://docs.python.org/3/library/functions.html#max",
  },
  {
    id: "mc6",
    type: "mc",
    topic: "Strings",
    question: "What does 'hello world'.split() return?",
    options: [
      "['hello', 'world']",
      "['h','e','l','l','o',' ','w','o','r','l','d']",
      "('hello', 'world')",
      "Error — no separator specified",
    ],
    answer: "['hello', 'world']",
    explanation: "split() with no argument splits on any whitespace and strips leading/trailing whitespace.",
    link: "https://docs.python.org/3/library/stdtypes.html#str.split",
  },
  {
    id: "mc7",
    type: "mc",
    topic: "Dicts",
    question: "What does dict.get('missing_key', 'default') return if the key doesn't exist?",
    options: ["None", "KeyError", "'default'", "False"],
    answer: "'default'",
    explanation: ".get() returns the second argument as a fallback instead of raising KeyError.",
    link: "https://docs.python.org/3/library/stdtypes.html#dict.get",
  },
  {
    id: "mc8",
    type: "mc",
    topic: "Built-ins",
    question: "What is the output of sorted([3, 1, 2], reverse=True)?",
    options: ["[1, 2, 3]", "[3, 2, 1]", "[3, 1, 2]", "None"],
    answer: "[3, 2, 1]",
    explanation: "sorted() returns a new sorted list. reverse=True gives descending order.",
    link: "https://docs.python.org/3/library/functions.html#sorted",
  },
  {
    id: "mc9",
    type: "mc",
    topic: "Comprehensions",
    question: "What does [x**2 for x in range(4)] produce?",
    options: ["[1, 4, 9, 16]", "[0, 1, 4, 9]", "[0, 1, 2, 3]", "[1, 2, 3, 4]"],
    answer: "[0, 1, 4, 9]",
    explanation: "range(4) is 0–3. Squaring each: 0, 1, 4, 9.",
    link: "https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions",
  },
  {
    id: "mc10",
    type: "mc",
    topic: "Built-ins",
    question: "What does enumerate(['a', 'b', 'c']) yield on its first iteration?",
    options: ["'a'", "(0, 'a')", "(1, 'a')", "0"],
    answer: "(0, 'a')",
    explanation: "enumerate() yields (index, value) tuples. Default start index is 0.",
    link: "https://docs.python.org/3/library/functions.html#enumerate",
  },
  {
    id: "mc11",
    type: "mc",
    topic: "Built-ins",
    question: "What is zip([1,2,3], ['a','b','c']) most similar to?",
    options: [
      "Concatenating two lists",
      "Pairing elements by position into tuples",
      "Interleaving two lists",
      "Creating a dictionary",
    ],
    answer: "Pairing elements by position into tuples",
    explanation: "zip() pairs elements at the same index: (1,'a'), (2,'b'), (3,'c').",
    link: "https://docs.python.org/3/library/functions.html#zip",
  },
  {
    id: "mc12",
    type: "mc",
    topic: "Strings",
    question: "What does ', '.join(['a', 'b', 'c']) return?",
    options: ["['a', 'b', 'c']", "'a, b, c'", "'a b c'", "Error"],
    answer: "'a, b, c'",
    explanation: "join() concatenates list elements with the string as a separator.",
    link: "https://docs.python.org/3/library/stdtypes.html#str.join",
  },
  {
    id: "mc13",
    type: "mc",
    topic: "Slicing",
    question: "How do you get the last 3 elements of a list?",
    options: ["lst[:-3]", "lst[-3]", "lst[-3:]", "lst[len(lst)-3]"],
    answer: "lst[-3:]",
    explanation: "Negative indices count from the end. -3: means 'from 3rd-to-last through end'.",
    link: "https://docs.python.org/3/library/stdtypes.html#common-sequence-operations",
  },
  {
    id: "mc14",
    type: "mc",
    topic: "Dicts",
    question: "Which creates a dict from two lists of keys and values?",
    options: [
      "dict(keys, values)",
      "dict(zip(keys, values))",
      "{keys: values}",
      "dict.fromkeys(keys, values)",
    ],
    answer: "dict(zip(keys, values))",
    explanation: "zip pairs them up, dict() converts the resulting tuples into key-value pairs.",
    link: "https://docs.python.org/3/library/stdtypes.html#dict",
  },
  {
    id: "mc15",
    type: "mc",
    topic: "Built-ins",
    question: "What is the result of any([False, False, True])?",
    options: ["False", "True", "[False, False, True]", "1"],
    answer: "True",
    explanation: "any() returns True if at least one element is truthy.",
    link: "https://docs.python.org/3/library/functions.html#any",
  },

  // --- FILL IN THE BLANK ---
  {
    id: "fb1",
    type: "fitb",
    topic: "Slicing",
    question: "To get a copy of a list (shallow copy via slice), you write: lst[___]",
    answer: ["::", ":"],
    displayAnswer: "lst[:]  or  lst[::]",
    explanation: "An empty slice [:] copies the full list. [::] works too but [:] is idiomatic.",
    link: "https://docs.python.org/3/library/stdtypes.html#common-sequence-operations",
  },
  {
    id: "fb2",
    type: "fitb",
    topic: "Built-ins",
    question: "To add up a list of numbers: total = ___(numbers)",
    answer: ["sum"],
    displayAnswer: "sum(numbers)",
    explanation: "sum() works on any iterable of numbers.",
    link: "https://docs.python.org/3/library/functions.html#sum",
  },
  {
    id: "fb3",
    type: "fitb",
    topic: "Strings",
    question: "To divide a string on commas: parts = s.___(',')",
    answer: ["split"],
    displayAnswer: "s.split(',')",
    explanation: ".split(sep) splits on the given separator.",
    link: "https://docs.python.org/3/library/stdtypes.html#str.split",
  },
  {
    id: "fb4",
    type: "fitb",
    topic: "Comprehensions",
    question: "List comprehension for even numbers 0–9:\nevens = [x for x in range(10) if x % 2 ___ 0]",
    answer: ["=="],
    displayAnswer: "== 0",
    explanation: "The if clause filters elements. x % 2 == 0 is the even check.",
    link: "https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions",
  },
  {
    id: "fb5",
    type: "fitb",
    topic: "Dicts",
    question: "Safely retrieve a value with fallback:\nval = my_dict.___('key', None)",
    answer: ["get"],
    displayAnswer: ".get('key', None)",
    explanation: ".get() avoids KeyError and returns the fallback if the key is missing.",
    link: "https://docs.python.org/3/library/stdtypes.html#dict.get",
  },
  {
    id: "fb6",
    type: "fitb",
    topic: "Built-ins",
    question: "To loop with index and value:\nfor i, v in ___(my_list):",
    answer: ["enumerate"],
    displayAnswer: "enumerate(my_list)",
    explanation: "enumerate() yields (index, value) pairs — avoids manual counter variables.",
    link: "https://docs.python.org/3/library/functions.html#enumerate",
  },
  {
    id: "fb7",
    type: "fitb",
    topic: "Slicing",
    question: "Reverse a string s without calling .reverse():\nreversed_s = s[___]",
    answer: ["::-1"],
    displayAnswer: "s[::-1]",
    explanation: "Step -1 with no start/end reverses any sequence. Works on strings and lists.",
    link: "https://docs.python.org/3/library/stdtypes.html#common-sequence-operations",
  },
  {
    id: "fb8",
    type: "fitb",
    topic: "Strings",
    question: "Join a list of words into a space-separated string:\nresult = ' '.___( words )",
    answer: ["join"],
    displayAnswer: "' '.join(words)",
    explanation: ".join() is called on the separator string, not the list — easy to forget.",
    link: "https://docs.python.org/3/library/stdtypes.html#str.join",
  },
  {
    id: "fb9",
    type: "fitb",
    topic: "Built-ins",
    question: "Sort a list of tuples by the second element:\nsorted(pairs, key=___ x: x[1])",
    answer: ["lambda"],
    displayAnswer: "key=lambda x: x[1]",
    explanation: "lambda defines an inline function. key= tells sorted() what to sort by.",
    link: "https://docs.python.org/3/reference/expressions.html#lambda",
  },
  {
    id: "fb10",
    type: "fitb",
    topic: "Built-ins",
    question: "Check if all elements in a list are positive:\nresult = ___(x > 0 for x in nums)",
    answer: ["all"],
    displayAnswer: "all(x > 0 for x in nums)",
    explanation: "all() with a generator expression is clean and Pythonic — no intermediate list needed.",
    link: "https://docs.python.org/3/library/functions.html#all",
  },
];
