export const meta = {
  id: "python-classes",
  title: "Python Classes & Inheritance",
  description: "OOP fundamentals: classes, instances, inheritance, super(), dunder methods",
  topics: ["Classes", "Inheritance", "Dunders", "Instances"],
};

export const questions = [
  // --- MULTIPLE CHOICE ---
  {
    id: "mc1",
    type: "mc",
    topic: "Classes",
    question: "What is the first parameter of every instance method by convention?",
    options: ["this", "self", "cls", "obj"],
    answer: "self",
    explanation: "self refers to the instance the method is called on. It's a convention, not a keyword — but don't fight it.",
    link: "https://docs.python.org/3/tutorial/classes.html#method-objects",
  },
  {
    id: "mc2",
    type: "mc",
    topic: "Classes",
    question: "Which method is called automatically when a new instance is created?",
    options: ["__new__", "__create__", "__init__", "__start__"],
    answer: "__init__",
    explanation: "__init__ initializes the instance after it's created. It's the constructor you'll use 99% of the time.",
    link: "https://docs.python.org/3/reference/datamodel.html#object.__init__",
  },
  {
    id: "mc3",
    type: "mc",
    topic: "Classes",
    question: "What is the difference between a class attribute and an instance attribute?",
    options: [
      "There is no difference",
      "Class attributes are defined in __init__; instance attributes are defined outside it",
      "Class attributes are shared across all instances; instance attributes belong to one instance",
      "Instance attributes are read-only",
    ],
    answer: "Class attributes are shared across all instances; instance attributes belong to one instance",
    explanation: "A class attribute lives on the class itself and is shared. An instance attribute is set on self and is unique to that object.",
    link: "https://docs.python.org/3/tutorial/classes.html#class-and-instance-variables",
  },
  {
    id: "mc4",
    type: "mc",
    topic: "Inheritance",
    question: "Given class Dog(Animal):, what does Animal serve as?",
    options: ["A mixin", "The base (parent) class", "An interface", "A metaclass"],
    answer: "The base (parent) class",
    explanation: "The class in parentheses is the parent. Dog inherits all of Animal's methods and attributes.",
    link: "https://docs.python.org/3/tutorial/classes.html#inheritance",
  },
  {
    id: "mc5",
    type: "mc",
    topic: "Inheritance",
    question: "What does super() return?",
    options: [
      "The parent class itself",
      "A proxy object that delegates method calls to the parent class",
      "A copy of the current instance",
      "The grandparent class",
    ],
    answer: "A proxy object that delegates method calls to the parent class",
    explanation: "super() gives you a proxy that follows the MRO to find the next class in line — usually the parent.",
    link: "https://docs.python.org/3/library/functions.html#super",
  },
  {
    id: "mc6",
    type: "mc",
    topic: "Inheritance",
    question: "What is the output?\n\nclass A:\n    def greet(self):\n        return 'A'\n\nclass B(A):\n    def greet(self):\n        return 'B'\n\nprint(B().greet())",
    options: ["A", "B", "AB", "Error"],
    answer: "B",
    explanation: "B overrides greet(). Python looks up methods on the instance's class first, so B's version wins.",
    link: "https://docs.python.org/3/tutorial/classes.html#inheritance",
  },
  {
    id: "mc7",
    type: "mc",
    topic: "Dunders",
    question: "Which dunder method controls the string returned by print(obj)?",
    options: ["__repr__", "__str__", "__print__", "__format__"],
    answer: "__str__",
    explanation: "__str__ is for human-readable output and is what print() uses. __repr__ is for developer/debugging output.",
    link: "https://docs.python.org/3/reference/datamodel.html#object.__str__",
  },
  {
    id: "mc8",
    type: "mc",
    topic: "Instances",
    question: "What does isinstance(obj, MyClass) return if obj is an instance of a subclass of MyClass?",
    options: ["False", "True", "None", "TypeError"],
    answer: "True",
    explanation: "isinstance() checks the full inheritance chain. A subclass instance IS an instance of the parent class.",
    link: "https://docs.python.org/3/library/functions.html#isinstance",
  },
  {
    id: "mc9",
    type: "mc",
    topic: "Classes",
    question: "What decorator turns a method into one that receives the class instead of the instance?",
    options: ["@staticmethod", "@classmethod", "@property", "@abstractmethod"],
    answer: "@classmethod",
    explanation: "@classmethod passes cls (the class) as the first argument instead of self (the instance). Useful for alternative constructors.",
    link: "https://docs.python.org/3/library/functions.html#classmethod",
  },
  {
    id: "mc10",
    type: "mc",
    topic: "Inheritance",
    question: "Python supports multiple inheritance. What is the MRO?",
    options: [
      "Method Return Order — the order methods return values",
      "Method Resolution Order — the order Python searches classes for a method",
      "Multiple Resolution Object — an object that holds all parent classes",
      "Memory Register Object — how Python allocates class memory",
    ],
    answer: "Method Resolution Order — the order Python searches classes for a method",
    explanation: "The MRO (C3 linearization) defines the order Python searches classes when looking up a method. Use ClassName.__mro__ to inspect it.",
    link: "https://docs.python.org/3/howto/mro.html",
  },
  {
    id: "mc11",
    type: "mc",
    topic: "Dunders",
    question: "Which dunder method lets you use len(obj)?",
    options: ["__size__", "__count__", "__len__", "__length__"],
    answer: "__len__",
    explanation: "Implementing __len__ makes your object work with the built-in len() function.",
    link: "https://docs.python.org/3/reference/datamodel.html#object.__len__",
  },
  {
    id: "mc12",
    type: "mc",
    topic: "Classes",
    question: "What does @staticmethod do differently from @classmethod?",
    options: [
      "staticmethod receives self; classmethod does not",
      "staticmethod receives neither self nor cls — it's just a regular function namespaced to the class",
      "staticmethod can only be called on the class, not instances",
      "There is no difference",
    ],
    answer: "staticmethod receives neither self nor cls — it's just a regular function namespaced to the class",
    explanation: "A static method is a plain function that lives inside a class for organizational reasons. No access to instance or class state.",
    link: "https://docs.python.org/3/library/functions.html#staticmethod",
  },
  {
    id: "mc13",
    type: "mc",
    topic: "Inheritance",
    question: "What happens if a child class defines __init__ without calling super().__init__()?",
    options: [
      "SyntaxError at definition time",
      "The parent's __init__ runs anyway",
      "The parent's __init__ is skipped — parent setup code won't run",
      "Python raises a RuntimeError",
    ],
    answer: "The parent's __init__ is skipped — parent setup code won't run",
    explanation: "You must explicitly call super().__init__() if you want the parent to initialize. Python won't call it for you.",
    link: "https://docs.python.org/3/library/functions.html#super",
  },
  {
    id: "mc14",
    type: "mc",
    topic: "Dunders",
    question: "Which dunder makes obj1 + obj2 work on your custom class?",
    options: ["__plus__", "__combine__", "__add__", "__sum__"],
    answer: "__add__",
    explanation: "Dunder methods map to operators. __add__ → +, __sub__ → -, __mul__ → *, etc.",
    link: "https://docs.python.org/3/reference/datamodel.html#emulating-numeric-types",
  },
  {
    id: "mc15",
    type: "mc",
    topic: "Instances",
    question: "What does vars(obj) return?",
    options: [
      "A list of method names",
      "The object's __dict__ — its instance attributes as a dictionary",
      "The class's attributes",
      "A list of all attribute names as strings",
    ],
    answer: "The object's __dict__ — its instance attributes as a dictionary",
    explanation: "vars(obj) is equivalent to obj.__dict__. It shows only instance attributes, not methods or class attributes.",
    link: "https://docs.python.org/3/library/functions.html#vars",
  },

  // --- FILL IN THE BLANK ---
  {
    id: "fb1",
    type: "fitb",
    topic: "Classes",
    question: "Define a class named Car:\nclass ___(object):",
    answer: ["Car"],
    displayAnswer: "class Car(object):",
    explanation: "Class names use PascalCase by convention. Inheriting from object is implicit in Python 3 but some write it explicitly.",
    link: "https://docs.python.org/3/tutorial/classes.html#a-first-look-at-classes",
  },
  {
    id: "fb2",
    type: "fitb",
    topic: "Classes",
    question: "Set an instance attribute inside __init__:\ndef __init__(self, name):\n    ___.name = name",
    answer: ["self"],
    displayAnswer: "self.name = name",
    explanation: "self refers to the instance being created. Assigning to self.x creates an instance attribute.",
    link: "https://docs.python.org/3/tutorial/classes.html#class-and-instance-variables",
  },
  {
    id: "fb3",
    type: "fitb",
    topic: "Inheritance",
    question: "Call the parent class's __init__ from a child:\ndef __init__(self, name):\n    ___().___init___(name)",
    answer: ["super().__init__"],
    displayAnswer: "super().__init__(name)",
    explanation: "super().__init__() delegates to the parent's constructor. Always call it when the parent has setup logic.",
    link: "https://docs.python.org/3/library/functions.html#super",
  },
  {
    id: "fb4",
    type: "fitb",
    topic: "Dunders",
    question: "Make print(obj) output something readable:\ndef ___(self):\n    return f'Car({self.name})'",
    answer: ["__str__"],
    displayAnswer: "__str__",
    explanation: "__str__ is called by print() and str(). Return a human-friendly string.",
    link: "https://docs.python.org/3/reference/datamodel.html#object.__str__",
  },
  {
    id: "fb5",
    type: "fitb",
    topic: "Instances",
    question: "Check if obj is an instance of Vehicle:\n___(obj, Vehicle)",
    answer: ["isinstance"],
    displayAnswer: "isinstance(obj, Vehicle)",
    explanation: "isinstance() is the idiomatic way to check type, and it respects inheritance.",
    link: "https://docs.python.org/3/library/functions.html#isinstance",
  },
  {
    id: "fb6",
    type: "fitb",
    topic: "Classes",
    question: "Define an alternative constructor using a class method:\n@___\ndef from_string(cls, s):\n    ...",
    answer: ["classmethod"],
    displayAnswer: "@classmethod",
    explanation: "@classmethod is commonly used for alternative constructors that create instances from different input formats.",
    link: "https://docs.python.org/3/library/functions.html#classmethod",
  },
  {
    id: "fb7",
    type: "fitb",
    topic: "Inheritance",
    question: "Check if Dog is a subclass of Animal:\n___(Dog, Animal)",
    answer: ["issubclass"],
    displayAnswer: "issubclass(Dog, Animal)",
    explanation: "issubclass() checks the class hierarchy. Unlike isinstance(), both arguments are classes (not instances).",
    link: "https://docs.python.org/3/library/functions.html#issubclass",
  },
  {
    id: "fb8",
    type: "fitb",
    topic: "Classes",
    question: "Define a shared counter across all instances:\nclass MyClass:\n    ___ = 0",
    answer: ["count", "counter"],
    displayAnswer: "count = 0",
    explanation: "A variable defined directly in the class body (not inside a method) is a class attribute, shared by all instances.",
    link: "https://docs.python.org/3/tutorial/classes.html#class-and-instance-variables",
  },
  {
    id: "fb9",
    type: "fitb",
    topic: "Dunders",
    question: "Support len(obj) on your class:\ndef ___(self):\n    return len(self.items)",
    answer: ["__len__"],
    displayAnswer: "__len__",
    explanation: "Implementing __len__ plugs your class into Python's built-in len() function.",
    link: "https://docs.python.org/3/reference/datamodel.html#object.__len__",
  },
  {
    id: "fb10",
    type: "fitb",
    topic: "Instances",
    question: "Get all instance attributes as a dict:\nattrs = ___(obj)",
    answer: ["vars"],
    displayAnswer: "vars(obj)",
    explanation: "vars(obj) returns obj.__dict__ — a dict of the instance's own attributes.",
    link: "https://docs.python.org/3/library/functions.html#vars",
  },
];
